cassandra_version: 3.11.4
cassandra_dir: "apache-cassandra-{{ cassandra_version }}"
cassandra_file: "{{ cassandra_dir }}-bin.tar.gz"

cassandra_download_url: "http://www-eu.apache.org/dist/cassandra/{{ cassandra_version }}/{{ cassandra_file }}"
cassandra_checksum_url: "{{ cassandra_download_url}}.sha512"
cassandra_checksum: "files/{{ cassandra_file }}.sha512"
cassandra_home: "/opt/{{ cassandra_dir }}"
