---

spark_download_base_url: "http://archive.apache.org/dist/spark/"
hadoop_vars:
  "1":
    url: "http://archive.apache.org/dist/hadoop/common/hadoop-1.2.1/hadoop-1.2.1.tar.gz"
    archived_name: "hadoop-1.2.1.tar.gz"
    folder_name:  "hadoop-1.2.1"
    suffix: "hadoop1"
    swift_lib_url: False
    swift_lib_name: False
  "2.3":
    url: "http://archive.apache.org/dist/hadoop/common/hadoop-2.3.0/hadoop-2.3.0.tar.gz"
    archived_name: "hadoop-2.3.0.tar.gz"
    folder_name:  "hadoop-2.3.0"
    suffix: "hadoop2.3"
    swift_lib_url: "https://repository.cloudera.com/artifactory/repo/org/apache/hadoop/hadoop-openstack/2.3.0-cdh5.1.7/hadoop-openstack-2.3.0-cdh5.1.7.jar"
    swift_lib_name: "hadoop-openstack-2.3.0-cdh5.1.7.jar"
  "2.4":
    url: "http://archive.apache.org/dist/hadoop/common/hadoop-2.4.1/hadoop-2.4.1.tar.gz"
    archived_name: "hadoop-2.4.1.tar.gz"
    folder_name:  "hadoop-2.4.1"
    suffix: "hadoop2.4"
    swift_lib_url: False
    swift_lib_name: False"
  "2.6":
    url: "http://archive.apache.org/dist/hadoop/common/hadoop-2.6.0/hadoop-2.6.0.tar.gz"
    archived_name: "hadoop-2.6.0.tar.gz"
    folder_name: "hadoop-2.6.0"
    suffix: "hadoop2.6"
    swift_lib_url: "https://repository.cloudera.com/artifactory/repo/org/apache/hadoop/hadoop-openstack/2.6.0-cdh5.9.3/hadoop-openstack-2.6.0-cdh5.9.3.jar"
    swift_lib_name: "hadoop-openstack-2.6.0-cdh5.9.3.jar"
  "2.7":
    url: "http://archive.apache.org/dist/hadoop/common/hadoop-2.7.3/hadoop-2.7.3.tar.gz"
    archived_name: "hadoop-2.7.3.tar.gz"
    folder_name: "hadoop-2.7.3"
    suffix: "hadoop2.7"
    swift_lib_url: False
    swift_lib_name: False
  "cdh4":
    url: "https://archive.cloudera.com/cdh4/cdh/4/hadoop-2.0.0-cdh4.7.1.tar.gz"
    archived_name: "hadoop-2.0.0-cdh4.7.1.tar.gz"
    folder_name: "hadoop-2.0.0-cdh4.7.1"
    suffix: "cdh4"
    swift_lib_url: False
    swift_lib_name: False


spark_download_url: "{{ spark_download_base_url }}spark-{{ spark_version }}/spark-{{ spark_version }}-bin-{{ hadoop_vars[hadoop_version]['suffix'] }}.tgz"
spark_checksum_url: "{{ spark_download_url }}.md5"
spark_arch: "files/spark-{{ spark_version }}-bin-{{ hadoop_vars[hadoop_version]['suffix'] }}.tgz"
spark_arch_checksum: "{{ spark_arch }}.md5"
spark_file: "spark-{{ spark_version }}-bin-{{ hadoop_vars[hadoop_version]['suffix'] }}"
spark_home: "/opt/{{ spark_file }}"

hadoop_download_url: "{{ hadoop_vars[hadoop_version]['url'] }}"
hadoop_checksum_url: "{{ hadoop_download_url }}.mds"
hadoop_arch: "files/{{ hadoop_vars[hadoop_version]['archived_name'] }}"
hadoop_arch_checksum: "{{ hadoop_arch }}.mds"
hadoop_file: "{{ hadoop_vars[hadoop_version]['folder_name'] }}"
hadoop_home: "/usr/local/{{ hadoop_file }}"

swift_download_url: "{{ hadoop_vars[hadoop_version]['swift_lib_url'] }}"
swift_lib: "files/{{ hadoop_vars[hadoop_version]['swift_lib_name'] }}"
swift_lib_destination: "{{ hadoop_home }}/share/hadoop/hdfs/lib/{{ hadoop_vars[hadoop_version]['swift_lib_name'] }}"

hadoop_user: "{{ hadoop_user }}"
do_prepare: False
detect_conf: False

is_master: "{{ inventory_hostname in groups[master_group_name] }}"

#FIXME: undefined vars for scripts
spark_local_dirs: TODO
spark_master_opts: TODO
spark_worker_instances: TODO

spark_extra_jars_dir: "{{ spark_home }}/lib_extra"
spark_extra_jars_list: "{% for jar in extra_jars|default([]) %}:{{spark_extra_jars_dir}}/{{jar.name}}{% endfor %}"

use_yarn: False
