---

- hosts: localhost
  become: no
  tasks:
    - name: create security group
      os_security_group:
        state: present
        name: "{{ cluster_name }}"
        description: "Security group for running {{ cluster_name }}"

    - os_security_group_rule:
        security_group: "{{ cluster_name }}"
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0

    - os_security_group_rule:
        security_group: "{{ cluster_name }}"
        protocol: tcp
        remote_ip_prefix: 0.0.0.0/0

    - os_security_group_rule:
        security_group: "{{ cluster_name }}"
        protocol: udp
        remote_ip_prefix: 0.0.0.0/0

    - name: create an instance
      os_server:
        name: "{{ cluster_name }}-runner"
        state: present
        image: "{{ os_image }}"
        flavor: "{{ master_flavor }}"
        key_name: "{{ os_key_name }}"
        floating_ip_pools: "{{ floating_ip_pool }}"
        network: "{{ virtual_network }}"
        boot_from_volume: "{{ boot_from_volume }}"
        security_groups: "{{ cluster_name }}"
        meta:
          group: "{{ cluster_name }}_runner"
          hostname: "{{ cluster_name }}-runner"

    # Delay for correct connection to the created instances
    - pause:
        echo: no
        seconds: 10

    - name: Register runner facts
      os_server_facts:
        filters:
          metadata:
            hostname: "{{ cluster_name }}-runner"

    - name: Make up inventory
      add_host:
        name: "{{ item.name }}"
        groups: "{{ cluster_name }}_runner"
        ansible_host: "{{ item.public_v4 }}"
        ansible_ssh_host: "{{ item.interface_ip }}"
        ansible_user: "ubuntu"
        openstack: "{{ item }}"
      with_items:
        - "{{ openstack_servers }}"

- hosts: "{{ cluster_name }}_runner"
  become: yes
  tasks:
    - name: install python
      apt:
        name: python2.7
        update_cache: yes

    - name: install pip
      apt:
        name: python-pip
        update_cache: yes

    - name: use actual ansible repo
      apt_repository:
        repo: ppa:ansible/ansible
        
    - name: install ansible
      apt:
        name: ansible
        update_cache: yes

    - name: install openstack SDK
      pip:
        name: openstacksdk
        version: 0.31.0
        executable: pip

    - name: clone spark-openstack project
      become: no
      git:
        repo: "https://github.com/ispras/spark-openstack.git"
        dest: "/home/ubuntu/spark-openstack/"