---

- hosts: localhost
  roles:
    - os_facts
  tasks:
    - debug: var=active_master

- hosts: "{{ cluster_name }}_master"
  roles:
    - { role: spark_common, detect_conf: True }
  tasks:
    - include: tasks/stop_all.yml

- hosts: "{{ cluster_name }}_master:{{ cluster_name }}_slaves"
  become: True
  vars:
    clear_logs: False
  tasks:
    - name: kill all java processes
      command: killall -9 java
      ignore_errors: yes

    - name: clear worker logs
      shell: rm -rv /opt/spark/work/*
      ignore_errors: True
      when: clear_logs

- hosts: "{{ cluster_name }}_master"
  roles:
    - { role: spark_common, detect_conf: True }
  tasks:
    - include: tasks/start_all.yml